In [1]:
from google.colab import drive # Mounte personal Gdrive folder
drive.mount('/content/drive')

Mounted at /content/drive

###Install lib, import module and read data

In [2]:
!pip install ydata-profiling
!python -m spacy download en_core_web_lg

Collecting ydata-profiling
  Downloading ydata_profiling-4.12.2-py2.py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.10.6)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.5)
Collecting visions<0.8.0,>=0.7.5 (from visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling)
  Downloading visions-0.7.6-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.26.4)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.1)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.1-py3-none-any.whl.metadata (17 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (4.55.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2025.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.12.14)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.0,>=0.7.5->visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling) (25.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.0,>=0.7.5->visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.12.2-py2.py3-none-any.whl (390 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.9/390.9 kB 6.7 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 29.3 MB/s eta 0:00:00
Downloading dacite-1.9.1-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 28.8 MB/s eta 0:00:00
Downloading visions-0.7.6-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 11.5 MB/s eta 0:00:00
Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 83.6 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=3afde51d869a291762b51d6c3aeb686546d69db2792bb7eb3cb5dd59dab422f6
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: htmlmin, PyWavelets, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed PyWavelets-1.8.0 dacite-1.9.1 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 visions-0.7.6 ydata-profiling-4.12.2
Collecting en-core-web-lg==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl (587.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.2 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.11/dist-packages (from en-core-web-lg==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.10.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.1.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2024.12.14)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.2)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
import pandas as pd
from ydata_profiling import ProfileReport
import numpy as np
from datetime import datetime
import re
import spacy

# Load the large English model
nlp = spacy.load('en_core_web_lg')

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/zyl009/DATA-AND-INFORMATION-QUALITY-PROJECT/refs/heads/main/attacks.csv')
data= pd.DataFrame(data)

###DATA EXPLORATION

In [5]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2017.06.11,2017-06-11,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,...,N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6095
1,2017.06.10.b,2017-06-10,2017.0,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,...,N,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.b,2017.06.10.b,6094
2,2017.06.10.a,2017-06-10,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,...,N,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.a,2017.06.10.a,6093
3,2017.06.07.R,Reported 07-Jun-2017,2017.0,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,...,N,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.07.R,2017.06.07.R,6092
4,2017.06.04,2017-06-04,2017.0,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,...,N,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.04,2017.06.04,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6
6090,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5
6091,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4
6092,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3
6093,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2

In [ ]:
data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [ ]:
data.shape

(6094, 22)

In [ ]:
data.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order              int64
dtype: object

In [ ]:
data.describe()

              Year  original order
count  6092.000000     6094.000000
mean   1926.197308     3048.499672
std     284.366422     1759.331064
min       0.000000        2.000000
25%    1942.000000     1525.250000
50%    1976.000000     3048.500000
75%    2004.000000     4571.750000
max    2017.000000     6095.000000

In [ ]:
data.duplicated().any()

False

###(1)PROFILING

In [ ]:
PROFILE = ProfileReport(data, title="Pandas Profiling Report")
PROFILE.to_file("profiling.html")
PROFILE

Output hidden; open in https://colab.research.google.com to view.

###(2)DQ ASSESSMENT

In [ ]:
for col in data.columns:
    print("DQ Assessment for "+col+":")

    DISTINCT = (data[col].nunique())
    COUNT = data[col].count()
    ROWS = len(data[col])
    UNIQUENESS = DISTINCT / ROWS
    print("UNIQUENESS: ", UNIQUENESS)

    DISTINCTNESS = DISTINCT / COUNT
    print("DISTINCTNESS: ", DISTINCTNESS)

    MAX_COUNTS = max(data[col].value_counts())
    CONSTANCY = MAX_COUNTS / COUNT
    print("CONSTANCY: ", CONSTANCY)

    COMPLETENESS = COUNT / ROWS
    print("COMPLETENESS: ", COMPLETENESS)

    print("\n\n")

DQ Assessment for Case Number:
UNIQUENESS:  0.9973744666885461
DISTINCTNESS:  0.9973744666885461
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  1.0



DQ Assessment for Date:
UNIQUENESS:  0.8528060387266163
DISTINCTNESS:  0.8528060387266163
CONSTANCY:  0.0018050541516245488
COMPLETENESS:  1.0



DQ Assessment for Year:
UNIQUENESS:  0.03938299967180833
DISTINCTNESS:  0.03939592908732764
CONSTANCY:  0.02314510833880499
COMPLETENESS:  0.9996718083360683



DQ Assessment for Type:
UNIQUENESS:  0.0009845749917952085
DISTINCTNESS:  0.0009852216748768472
CONSTANCY:  0.7333333333333333
COMPLETENESS:  0.9993436166721366



DQ Assessment for Country:
UNIQUENESS:  0.033475549721037084
DISTINCTNESS:  0.03373015873015873
CONSTANCY:  0.35714285714285715
COMPLETENESS:  0.9924515917295701



DQ Assessment for Area:
UNIQUENESS:  0.13111256974072857
DISTINCTNESS:  0.14061950017599437
CONSTANCY:  0.1786342837029215
COMPLETENESS:  0.9323925172300623



DQ Assessment for Location:
UNIQUENESS:  0.6537577945520184
DISTINCTNESS:  0.7135948414830736
CONSTANCY:  0.029016657710908115
COMPLETENESS:  0.9161470298654414



DQ Assessment for Activity:
UNIQUENESS:  0.2466360354446997
DISTINCTNESS:  0.2703723691311387
CONSTANCY:  0.16747616477783775
COMPLETENESS:  0.9122087298982606



DQ Assessment for Name:
UNIQUENESS:  0.834591401378405
DISTINCTNESS:  0.8637907608695652
CONSTANCY:  0.0859375
COMPLETENESS:  0.9661962586150312



DQ Assessment for Sex :
UNIQUENESS:  0.0009845749917952085
DISTINCTNESS:  0.001087547580206634
CONSTANCY:  0.8892514047489578
COMPLETENESS:  0.9053167049556942



DQ Assessment for Age:
UNIQUENESS:  0.02477847062684608
DISTINCTNESS:  0.044754001185536456
CONSTANCY:  0.045050385299347954
COMPLETENESS:  0.5536593370528389



DQ Assessment for Injury:
UNIQUENESS:  0.5981293075155891
DISTINCTNESS:  0.6008902077151336
CONSTANCY:  0.12298054731289153
COMPLETENESS:  0.9954053167049557



DQ Assessment for Fatal (Y/N):
UNIQUENESS:  0.0014768624876928126
DISTINCTNESS:  0.001484168865435356
CONSTANCY:  0.7241094986807388
COMPLETENESS:  0.995077125041024



DQ Assessment for Time:
UNIQUENESS:  0.059074499507712507
DISTINCTNESS:  0.12640449438202248
CONSTANCY:  0.06355337078651685
COMPLETENESS:  0.46734492943879224



DQ Assessment for Species :
UNIQUENESS:  0.25500492287495896
DISTINCTNESS:  0.5014520813165537
CONSTANCY:  0.05292029686995805
COMPLETENESS:  0.5085329832622252



DQ Assessment for Investigator or Source:
UNIQUENESS:  0.7927469642271087
DISTINCTNESS:  0.7949646207010038
CONSTANCY:  0.015961823268059897
COMPLETENESS:  0.9972103708565803



DQ Assessment for pdf:
UNIQUENESS:  0.9981949458483754
DISTINCTNESS:  0.9981949458483754
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  1.0



DQ Assessment for href formula:
UNIQUENESS:  0.9980308500164096
DISTINCTNESS:  0.9981946495978993
CONSTANCY:  0.0003282455276546857
COMPLETENESS:  0.9998359041680341



DQ Assessment for href:
UNIQUENESS:  0.9970462750246144
DISTINCTNESS:  0.9972099130149352
CONSTANCY:  0.0006564910553093714
COMPLETENESS:  0.9998359041680341



DQ Assessment for Case Number.1:
UNIQUENESS:  0.9972103708565803
DISTINCTNESS:  0.9972103708565803
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  1.0



DQ Assessment for Case Number.2:
UNIQUENESS:  0.9973744666885461
DISTINCTNESS:  0.9973744666885461
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  1.0



DQ Assessment for original order:
UNIQUENESS:  0.9998359041680341
DISTINCTNESS:  0.9998359041680341
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  1.0

#(3) DATA CLEANING (DATA TRANSFORMATION)

In [ ]:
# Remove leading/trailing spaces for every col, fill empty with nan
for col in data.columns:
    if data[col].dtype == 'object':  # Check if the column contains string data
        data[col] = data[col].str.strip()
        # Replace empty strings with NaN
        data[col] = data[col].replace("", np.nan)

In [ ]:
#Remove specific symbols: @#$%^*�!? for every col
# function to clean special symbols
def remove_special_symbols(text):
    if pd.isna(text):  # Skip NaN values
        return text
    # Remove specific symbols: @#$%^*�!?
    text = re.sub(r'[#$%^*@�!?]', '', str(text))
    return text

# Apply cleaning to all object (text-based) columns
for col in data.select_dtypes(include=['object']).columns:
    data[col] = data[col].apply(remove_special_symbols)

##case number column

In [ ]:
data['Case Number'].equals(data['Case Number.1'].equals(data['Case Number.2']))

False

In [ ]:
data['Case Number'].equals(data['Case Number.1'])

False

In [ ]:
data['Case Number.1'].equals(data['Case Number.2'])

False

In [ ]:
data['Case Number'].isin(data['Case Number.1']).value_counts()

Case Number
True     6079
False      15
Name: count, dtype: int64

In [ ]:
data['Case Number'].isin(data['Case Number.2']).value_counts()

Case Number
True     6092
False       2
Name: count, dtype: int64

In [ ]:
data['Case Number.1'].isin(data['Case Number.2']).value_counts()

Case Number.1
True     6082
False      12
Name: count, dtype: int64

In [ ]:
#since Case Number, Case NumberN.1 and Case Number N.2 are similar, and they are just the number of the case, delete the Case Number.1 and Case Number.2
data=data.drop(['Case Number.1','Case Number.2'],axis=1)

##Date and Year and Time column

###normalize the date

In [ ]:
# Function to normalize date
def normalize_date(value):
    # Dictionary for month corrections and seasons mapping
    month_corrections = {
        "Jut": "Jul",
        "rch": "Mar",
        "ept": "Sep",
        "prr": "Apr",
        }
    seasons_mapping = {
        "Winter": "12-01",
        "Spring": "03-01",
        "Summer": "06-01",
        "Fall": "09-01",
    }

    # Correct common typos
    for typo, correct in month_corrections.items():
        value = value.replace(typo, correct)

    # Patterns
    season_year_pattern = r'(Winter|Spring|Summer|Fall)[^\d]*(\d{4})'  # e.g., Winter 1942
    day_month_year_pattern = r'(\d{1,2})-([A-Za-z]{3})-(\d{4})'  # e.g., 19-Jul-1913
    month_year_pattern = r'([A-Za-z]{3})-(\d{4})'  # e.g., Aug-1987
    year_pattern = r'(\d{4})'  # e.g., 1901

    try:
       # Handle YYYY-MM-DD (already formatted)
        if re.match(r'^\d{4}-\d{2}-\d{2}$', value):
            return value
        # Check if the value matches the format 'YYYY.MM.DD'
        match = re.match(r'^(\d{4})\.(\d{2})\.(\d{2})$', value)
        if match:
            year, month, day = match.groups()
            # Replace invalid month/day components
            month = '01' if month == '00' else month
            day = '01' if day == '00' else day
            return f"{year}-{month}-{day}"  # Return in 'YYYY-MM-DD' format
        # Match season and year
        match = re.search(season_year_pattern, value, re.IGNORECASE)
        if match:
            season, year = match.groups()
            month_day = seasons_mapping[season.capitalize()]
            return f"{year}-{month_day}"
        # Handle phrases like 'mid-1870s'
        if "mid" in value:
            match = re.search(r'(\d{4})', value)
            if match:
                year = match.group(1)
                return f"{year}-06-01"  # Approximate mid-year date

        # Match day-month-year
        match = re.search(day_month_year_pattern, value)
        if match:
            day, month, year = match.groups()
            month_num = datetime.strptime(month, "%b").month
            return f"{year}-{month_num:02d}-{int(day):02d}"

        # Match month-year
        match = re.search(month_year_pattern, value)
        if match:
            month, year = match.groups()
            month_num = datetime.strptime(month, "%b").month
            return f"{year}-{month_num:02d}-01"

        # Match year only
        match = re.search(year_pattern, value)
        if match:
            year = match.group(1)
            return f"{year}-01-01"

    except Exception as e:
        # Log unexpected errors for debugging
        print(f"Error processing value: {value}. Error: {e}")

    # Return None for unprocessable rows
    return np.nan

In [ ]:
# Example DataFrame
sampledata = pd.DataFrame({
    'Date': [
        '1986-01-02','2008.01.30','No date (3 days after preceding incident) & prior to 19-Jul-1913','Before 1903','Reported 09-Aprr-1855',
        'No date, Before Aug-1987', '1950s', '2003?', 'Ca. 1543','Circa 500 A.D.', 'Ca. 336.B.C.', 'Before Feb-1998', '190Feb-2010',
        'During the war 1943-1945','Summer-2008','25-Jut-1881','Reported 30-March-1878','Ca. mid-1870s','Reported 03-Sept-1816','Fall 1943','early winter 1993'
    ]
})

# Apply the function to the Date column
sampledata['Normalized Date'] = sampledata['Date'].apply(normalize_date)

# Display the updated DataFrame
sampledata

                                                 Date Normalized Date
0                                          1986-01-02      1986-01-02
1                                          2008.01.30      2008-01-30
2   No date (3 days after preceding incident) & pr...      1913-07-19
3                                         Before 1903      1903-01-01
4                               Reported 09-Aprr-1855      1855-04-01
5                            No date, Before Aug-1987      1987-08-01
6                                               1950s      1950-01-01
7                                               2003?      2003-01-01
8                                            Ca. 1543      1543-01-01
9                                      Circa 500 A.D.             NaN
10                                       Ca. 336.B.C.             NaN
11                                    Before Feb-1998      1998-02-01
12                                        190Feb-2010      2010-02-01
13                           During the war 1943-1945      1943-01-01
14                                        Summer-2008      2008-06-01
15                                        25-Jut-1881      1881-07-25
16                             Reported 30-March-1878      1878-03-01
17                                      Ca. mid-1870s      1870-06-01
18                              Reported 03-Sept-1816      1816-09-01
19                                          Fall 1943      1943-09-01
20                                  early winter 1993      1993-12-01

In [ ]:
# Apply the function to the Date column
data['Date'] = data['Date'].apply(normalize_date)

In [ ]:
# Convert Date column to datetime
data['Date']= pd.to_datetime(data['Date'],format='%Y-%m-%d',errors='coerce')

In [ ]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2017.06.11,2017-06-11,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6095
1,2017.06.10.b,2017-06-10,2017.0,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6094
2,2017.06.10.a,2017-06-10,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6093
3,2017.06.07.R,2017-06-07,2017.0,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6092
4,2017.06.04,2017-06-04,2017.0,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
6090,ND.0004,1903-01-01,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5
6091,ND.0003,1900-01-01,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
6092,ND.0002,1883-01-01,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8N, 79W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
6093,ND.0001,1845-01-01,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2

In [ ]:
# Convert the 'Year' column to integers (handling invalid or non-numeric values)
data['Year'] = pd.to_numeric(data['Year'], errors='coerce').fillna(0).astype(int)

###Time

In [ ]:
#move Time column next to the Date column
Time_to_move = data.pop('Time')  # Remove the column
data.insert(2, 'Time', Time_to_move)

In [ ]:
data['Time'].isnull().sum()

3250

In [ ]:
# Function to normalize time
def normalize_time(value):
    # Ensure the value is a string
    if not isinstance(value, str):
        return np.nan
    # Regex to find time already in HH:MM format
    match = re.search(r'\b(\d{1,2}):(\d{2})\b', value)
    if match:
        hour, minute = match.groups()
        return f"{int(hour):02d}:{int(minute):02d}"  # Return valid HH:MM format

    # Regex to find valid time patterns like hh:mm or hhm
    match = re.search(r'(\d{1,2})h(\d{2})', value)
    if match:
        hour, minute = match.groups()
        return f"{int(hour):02d}:{int(minute):02d}"

    # Map descriptions to approximate times
    time_map = {
        'early morning': '06:00',
        'late morning': '10:30',
        'morning': '08:00',
        'early afternoon': '13:00',
        'late afternoon': '16:30',
        'afternoon': '15:00',
        'late evening': '21:00',
        'evening': '19:00',
        'dusk': '18:30',
        'night': '22:00',
        'noon': '12:00',
        'midnight': '00:00'
      }
    for key, mapped_time in time_map.items():
        if key in value.lower():
            return mapped_time


    # Return None for unprocessable rows
    return np.nan


# Sample data
sampledTime = pd.DataFrame({
    'Time': ['08h00', 'wwwda15h00bdbgrfd', '15h45lll', 'Dusk','dusklllll', 'morning', 'MORNING','late late Late morning', 'siskks early afternoon', 'kcdoak night 6154', 'unknown']
})

# Apply normalization
sampledTime['Normalized Time'] = sampledTime['Time'].apply(normalize_time)
sampledTime

                      Time Normalized Time
0                    08h00           08:00
1        wwwda15h00bdbgrfd           15:00
2                 15h45lll           15:45
3                     Dusk           18:30
4                dusklllll           18:30
5                  morning           08:00
6                  MORNING           08:00
7   late late Late morning           10:30
8   siskks early afternoon           13:00
9        kcdoak night 6154           22:00
10                 unknown             NaN

In [ ]:
data['Time']=data['Time'].apply(normalize_time)

In [ ]:
data['Time']=pd.to_datetime(data['Time'],format='%H:%M',errors='coerce').dt.time

In [ ]:
data

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href formula,href,original order
0,2017.06.11,2017-06-11,08:30:00,2017,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6095
1,2017.06.10.b,2017-06-10,15:45:00,2017,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6094
2,2017.06.10.a,2017-06-10,10:00:00,2017,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6093
3,2017.06.07.R,2017-06-07,NaT,2017,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6092
4,2017.06.04,2017-06-04,NaT,2017,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
6090,ND.0004,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5
6091,ND.0003,1900-01-01,NaT,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
6092,ND.0002,1883-01-01,NaT,0,Unprovoked,PANAMA,NaN,"Panama Bay 8N, 79W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
6093,ND.0001,1845-01-01,NaT,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2

##Country, Area and Location column

###COUNTRY

In [ ]:
#Only one country (in the strings with '/' we will take only the first country)
#bring all the characters in uppercase
data["Country"] = data['Country'].str.title()
#adopt some convention in countries names (the country/country format I assume to be valid)
data.loc[data['Country'] == 'England', 'Country'] = 'United Kingdom'
data.loc[data['Country'] == 'Scotland', 'Country'] = 'United Kingdom'
data.loc[data['Country'] == 'Between Portugal & India', 'Country'] = 'Portugal / India'
data.loc[data['Country'] == 'Ceylon (Sri Lanka)', 'Country'] = 'Sri Lanka'

data[["Country","Country2"]] = data["Country"].str.split("/", expand = True)
data.drop("Country2", axis=1, inplace=True)

###AREA

In [ ]:
#Title string,illegible characters eliminated,No km/miles and so on, we take only the part of the string that contain the Area name

def standardize_area(area):
    if(pd.isna(area)):
      return np.nan

    # Remove numbers and "miles", "km", etc. (e.g., "16 miles off Hilton Head" -> "Hilton Head")
    area = re.sub(r'\d+\s*(miles|km|ft|yards|m)', '', area, flags=re.IGNORECASE)

    # Remove unnecessary punctuation or special characters (keep only letters, spaces, hyphens, apostrophes)
    area = re.sub(r'[^A-Za-z\s\'-,]', '', area)

    # Normalize spaces (replace multiple spaces with a single space)
    area = re.sub(r'\s+', ' ', area).strip()

    # Capitalize the first letter of each word (e.g., "new york" -> "New York")
    area = area.title()


    return area

In [ ]:
data['Area'] = data['Area'].apply(standardize_area)
data.loc[data['Area'] == '', 'Area'] = np.nan

###LOCATION

In [ ]:
def standardize_location(location):
    if(pd.isna(location)):
      return np.nan

    # Remove 'OFF', 'off', 'oFF', or 'Off' at the start of the 'Location' value
    location = re.sub(r'(?i)^\s*OFF', '', location)

    # Remove unnecessary punctuation or special characters (keep only letters, spaces, hyphens, apostrophes)
    location = re.sub(r'[^A-Za-z\s\'-,]', '', location)

    # Normalize spaces (replace multiple spaces with a single space)
    location = re.sub(r'\s+', ' ', location).strip()

    # Capitalize the first letter of each word (e.g., "new york" -> "New York")
    location = location.title()

    return location

In [ ]:
data['Location'] = data['Location'].apply(standardize_location)
data.loc[data['Location'] == '', 'Location'] = np.nan

In [ ]:
data['Location']

0                              Point Casuarina, Bunbury
1                         Flinders, Mornington Penisula
2                           Ponce Inlet, Volusia County
3                                         Bantham Beach
4       Middle Sambo Reef Off Boca Chica, Monroe County
                             ...
6089                                        Roebuck Bay
6090                                                NaN
6091                                     Ocracoke Inlet
6092                                    Panama Bay N, W
6093                Below The English Fort, Trincomalee
Name: Location, Length: 6094, dtype: object

##href column

In [ ]:
data['href formula'].equals(data['href'])

False

In [ ]:
data['href formula'].isin(data['href']).value_counts()

href formula
True     6040
False      54
Name: count, dtype: int64

In [ ]:
data.loc[data['href formula'] != data['href'], ['href formula', 'href']]

,href formula,href
0,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
8,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
35,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
99,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
106,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
141,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
187,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
194,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
214,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
261,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
313,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
344,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
345,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
346,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
353,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
354,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
375,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
387,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
405,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
430,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
444,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
445,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
446,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
447,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
448,http://sharkattackfile.net/spreadsheets/pdf_di...,pdf_directory2014.01.04-Riano.pdf
460,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
461,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
462,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
463,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
464,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
465,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
466,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
467,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
531,pdf-directory/2013.05.27.b-Ena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
532,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
906,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1301,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1302,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2561,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3103,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3104,VALUE,http://sharkattackfile.net/spreadsheets/pdf_di...
3633,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3687,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4001,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4012,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4479,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4728,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4754,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4805,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5403,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5545,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5773,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN
5781,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5913,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
#replace with correct value in href
data.loc[531,'href formula']=data['href'][531]
data.loc[3103,'href formula']=data['href'][3103]
data.loc[3104,'href formula']=data['href'][3104]

In [ ]:
#find rows where the 'href formular' column does not start with 'http'
invalid_urls = data[~data['href formula'].str.startswith('http', na=False)]
# Display rows with invalid URLs
invalid_urls

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href formula,href,original order
6008,ND.0100,2003-01-01,NaT,0,Unprovoked,Bahamas,Andros Islands,Great Guana Cay,Spearfishing,C.D. Dollar,M,NaN,Swim fin bitten,N,1.8 m [6'] shark,"R.D. Weeks, GSAF",ND-0100-CDDollar.pdf,Q93http://sharkattackfile.net/spreadsheets/pdf...,Q93http://sharkattackfile.net/spreadsheets/pdf...,87

In [ ]:
data.loc[6008,'href formula']=data.loc[6008,'href formula'].lstrip('Q93')
data.loc[6008,'href formula']

'http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0100-CDDollar.pdf'

In [ ]:
#delete href column since it is similar with href formula, and href fomula is more clean
del(data['href'])

In [ ]:
#rename href formula with href
data.rename(columns={'href formula': 'href'}, inplace=True)

###Original order column

In [ ]:
#Deleted the column 'original order' as it was uniformly distributed, not useful
del(data['original order'])

In [ ]:
data

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Unprovoked,Australia,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Unprovoked,Australia,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Unprovoked,Usa,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,Unprovoked,United Kingdom,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Unprovoked,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Unprovoked,Australia,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Unprovoked,Australia,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Unprovoked,Usa,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Unprovoked,Panama,NaN,"Panama Bay N, W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Unprovoked,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

##Type and Activity column

In [ ]:
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Invalid', 'Boat', 'Sea Disaster',
       'Boating'], dtype=object)

In [ ]:
#Type is related to the activity,  move 'Type' column next to the Activity column
Type_to_move = data.pop('Type')  # Remove the column
data.insert(7, 'Type', Type_to_move)

In [ ]:
data.insert(9,'Activity Detail',data['Activity'])

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Body boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Spearfishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Australia,Western Australia,NaN,Unprovoked,Pearl diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Panama,NaN,"Panama Bay N, W",Unprovoked,NaN,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data['Activity'].unique()

array(['Body boarding', 'Surfing', 'Spearfishing', ...,
       'Crew swimming alongside their anchored ship',
       '4 men were bathing', 'Wreck of  large double sailing canoe'],
      dtype=object)

In [ ]:
#main activity are swimming, Diving,surfing，boarding, fishing, Wading，Walking,Standing，Snorkeling，Bathing and Other
# Update the Activity column based on conditions
data['Activity'] = np.where(
    data['Activity'].str.contains('Swimming', case=False, na=False), 'Swimming',
    np.where(
        data['Activity'].str.contains('Diving', case=False, na=False), 'Diving',
        np.where(
        data['Activity'].str.contains('Surfing', case=False, na=False), 'Surfing',
        np.where(
        data['Activity'].str.contains('Boarding', case=False, na=False), 'Boarding',
        np.where(
        data['Activity'].str.contains('Fishing', case=False, na=False), 'Fishing',
        np.where(
        data['Activity'].str.contains('Wading', case=False, na=False), 'Wading',
        np.where(
        data['Activity'].str.contains('Walking', case=False, na=False), 'Walking',
        np.where(
        data['Activity'].str.contains('Standing', case=False, na=False), 'Standing',
        np.where(
        data['Activity'].str.contains('Snorkeling', case=False, na=False), 'Snorkeling',
        np.where(
        data['Activity'].str.contains('Bathing', case=False, na=False), 'Bathing',
        'Other'
))))))))))

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Australia,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Panama,NaN,"Panama Bay N, W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
#set No detail in Activity Detail column when data is the same in Activity and Activity Detail column
data.loc[data['Activity Detail'].str.lower()==data['Activity'].str.lower(),'Activity Detail']='No detail'

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Australia,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Panama,NaN,"Panama Bay N, W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Invalid', 'Boat', 'Sea Disaster',
       'Boating'], dtype=object)

In [ ]:
data.loc[data['Type']=='Invalid',['Type','Activity','Activity Detail']]

         Type  Activity Activity Detail
12    Invalid   Surfing       No detail
18    Invalid     Other     Photo shoot
20    Invalid  Swimming       No detail
26    Invalid    Diving    Scuba Diving
52    Invalid   Fishing    Spearfishing
...       ...       ...             ...
5941  Invalid   Bathing       No detail
5951  Invalid     Other             NaN
5957  Invalid     Other  Went overboard
6019  Invalid    Diving    Scuba diving
6024  Invalid    Diving       No detail

[529 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Boat',['Type','Activity','Activity Detail']]

      Type Activity                        Activity Detail
44    Boat  Fishing                          Kayak fishing
45    Boat    Other                         Tagging sharks
83    Boat  Fishing                              No detail
101   Boat    Other                               Kayaking
108   Boat  Fishing  Fishing in Alabama Deep Fishing Rodeo
...    ...      ...                                    ...
5925  Boat    Other                                    NaN
5932  Boat  Fishing                              No detail
5939  Boat    Other                                    NaN
6004  Boat  Fishing                              No detail
6066  Boat  Fishing                    Wooden fishing boat

[202 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Boating',['Type','Activity','Activity Detail']]

         Type  Activity                                    Activity Detail
4109  Boating   Fishing                                   Longling fishing
4111  Boating   Fishing                                          No detail
4114  Boating     Other                                            Boating
4131  Boating     Other                                       Ocean racing
4132  Boating   Fishing                                Fishing for pompano
...       ...       ...                                                ...
5715  Boating   Fishing                                          No detail
5720  Boating   Fishing                                          No detail
5722  Boating     Other  Fleet of canoes caught by a squall and charged...
5765  Boating   Fishing                                          No detail
5766  Boating  Boarding                                    Boarding a ship

[110 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Sea Disaster',['Type','Activity','Activity Detail']]

              Type  Activity                               Activity Detail
325   Sea Disaster     Other                                           NaN
448   Sea Disaster     Other                                  Sea disaster
751   Sea Disaster     Other                                  Sea disaster
1018  Sea Disaster     Other                                  Air Disaster
1049  Sea Disaster     Other          Sinking of the cargo ship Mark Jason
...            ...       ...                                           ...
5973  Sea Disaster     Other                                           NaN
6051  Sea Disaster     Other    A group of survivors on a raft for 17-days
6061  Sea Disaster     Other                                           NaN
6063  Sea Disaster     Other                        Spent 8 days in dinghy
6064  Sea Disaster  Swimming  Aircraft ditched in the sea, swimming ashore

[220 rows x 3 columns]

In [ ]:
#set boat as boating
data.loc[data['Type']=='Boat','Type']='Boating'

In [ ]:
# Update 'Activity' where 'Activity' is 'Other' and 'Type' is 'Boating' or 'Sea Distaster'
data.loc[(data['Activity'] == 'Other') & (data['Type'] == 'Boating'), 'Activity'] = 'Boating'
data.loc[(data['Activity'] == 'Other') & (data['Type'] =='Sea Disaster'),'Activity']='Sea Disaster'
#set No detail in Activity Detail column when data is the same in Activity and Activity Detail column
data.loc[data['Activity Detail'].str.lower()==data['Activity'].str.lower(),'Activity Detail']='No detail'

In [ ]:
#set Invalid, Boating and sea disaster as Unknown
data.loc[data['Type']=='Invalid','Type']='Unknown'
data.loc[data['Type']=='Boating','Type']='Unknown'
data.loc[data['Type']=='Sea Disaster','Type']='Unknown'
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Unknown'], dtype=object)

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Australia,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Panama,NaN,"Panama Bay N, W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

##Name, Sex and Age

###Name and Sex

In [ ]:
#Reomve illeggible characters
data["Name"] = data["Name"].apply(
    lambda s: re.sub(r'[^\x00-\x7F]+', '', str(s)) if not pd.isna(s) else s
)

In [ ]:
data.loc[data['Name'] == 'male', 'Name'] = 'M'
data.loc[data['Name'] == 'boy', 'Name'] = 'M'
data.loc[data['Name'] == 'female', 'Name'] = 'F'
data.loc[data['Name'] == 'girl', 'Name'] = 'F'

In [ ]:
data.rename(columns={'Sex ': 'Sex'}, inplace=True)

In [ ]:
data.loc[(data['Name'] == 'M')&(data['Sex'].isna()), 'Sex']

2084    NaN
2908    NaN
3152    NaN
4196    NaN
4325    NaN
5104    NaN
5870    NaN
5919    NaN
5967    NaN
Name: Sex, dtype: object

In [ ]:
data.loc[(data['Name'] == 'F')&(data['Sex'].isna()), 'Sex']

Series([], Name: Sex, dtype: object)

In [ ]:
data.loc[(data['Name'] == 'M')&(data['Sex'].isna()), 'Sex']='M'

In [ ]:
data.loc[data['Name'] == 'F', 'Name'] = np.nan
data.loc[data['Name'] == 'M', 'Name'] = np.nan
data["Name"] = data["Name"].str.title()

In [ ]:
##Using Spacy for identifying which are true names
def extract_name(name):
    if pd.isna(name):
        return np.nan
    doc = nlp(str(name))
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            return ent.text
    return np.nan

data["Name"] = data["Name"].apply(extract_name)

In [ ]:
data["Sex"].unique()

array(['M', 'F', nan, 'lli', 'N', '.'], dtype=object)

In [ ]:
data.loc[data['Sex'] == 'lli', 'Sex'] = np.nan
data.loc[data['Sex'] == 'N', 'Sex'] = np.nan
data.loc[data['Sex'] == '.', 'Sex'] = np.nan
data["Sex"].unique()

array(['M', 'F', nan], dtype=object)

###AGE

In [ ]:
print(data["Age"].dtype)
data["Age"]

object

0        48
1       NaN
2        19
3        30
4       NaN
       ...
6089    NaN
6090    NaN
6091    NaN
6092    NaN
6093     15
Name: Age, Length: 6094, dtype: object

In [ ]:
#delete 's' in tail of strings to normalize some ages (ex: 20s -> 20) and also I put 'Teen' in a established age of 18
data['Age'] = data['Age'].str.capitalize()
data['Age'] = data['Age'].str.strip("s")
data.loc[data['Age'] == 'Teen', 'Age'] = "18"

In [ ]:
#  Only one number is allowed，In case of more than one number I choose the first one
def standardize_age(age):
    if(pd.isna(age)):
      return np.nan
    pattern = r'\d+'
    match = re.search(pattern, age)
    if match:
        return match.group()
    return np.nan

In [ ]:
data["Age"] = data["Age"].apply(standardize_age)

##Injury and Fatal column

In [ ]:
data['Injury'].nunique()

3576

In [ ]:
# Remove 'PROVOKED INCIDENT' and the associated comma (if present)
data['Injury'] = data['Injury'].str.replace(r'(\s*,\s*)?PROVOKED INCIDENT(\s*,\s*)?', '', regex=True).str.strip()
data['Injury'] = data['Injury'].str.replace(r'(\s*,\s*)?FATAL(\s*,\s*)?', '', regex=True).str.strip()

In [ ]:
data['Fatal (Y/N)'].unique()

array(['N', 'Y', nan, 'UNKNOWN', '2017', 'F', 'VALUE', 'n'], dtype=object)

In [ ]:
data.rename(columns={'Fatal (Y/N)': 'Fatal'}, inplace=True)

In [ ]:
data.loc[data['Fatal']=='2017',['Injury','Fatal']]

                                       Injury Fatal
646  Lower left leg injured PROVOKED ACCIDENT  2017

In [ ]:
data.loc[data['Fatal']=='F',['Injury','Fatal']]

                          Injury Fatal
4779  human remains washed ahore     F

In [ ]:
data.loc[data['Fatal']=='VALUE',['Injury','Fatal']]

                                                 Injury  Fatal
5548  Forensic evidence indicated death resulted fro...  VALUE

In [ ]:
data.loc[data['Fatal']=='n',['Injury','Fatal']]

                  Injury Fatal
5870  Lacerations to leg     n

In [ ]:
data.loc[data['Fatal']=='N','Fatal']= 'NO'
data.loc[data['Fatal']=='Y','Fatal']= 'YES'
data.loc[data['Fatal']=='2017','Fatal']= 'NO'
data.loc[data['Fatal']=='F','Fatal']='YES'
data.loc[data['Fatal']=='VALUE','Fatal']='NO'
data.loc[data['Fatal']=='n','Fatal']='NO'

In [ ]:
data['Fatal'].unique()

array(['NO', 'YES', nan, 'UNKNOWN'], dtype=object)



##SPECIES

In [ ]:
data.rename(columns={'Species ': 'Species'}, inplace=True)

In [ ]:
#Split between Species and Size，identify the size of a shark and cast it into meters
def extract_size(s):
  s = str(s)

  match_float = re.search(r'\d+\.\d+', s)
  match_int = re.search(r'\d+', s)

  feet = False

  if '\'' in s:
    feet = True

# Check if a match is found
  if match_float:
    extracted_float = float(match_float.group())
    if feet:
      extracted_float *= 0.3048
    return extracted_float
  elif match_int:
    extracted_int = int(match_int.group())
    if feet:
      extracted_int *= 0.3048
    return extracted_int
  return np.nan

In [ ]:
data['Size[m]'] = data['Species'].apply(extract_size)
data['Size[m]']

0       4.0000
1       7.0000
2          NaN
3       3.0000
4       2.4384
         ...
6089       NaN
6090       NaN
6091       NaN
6092       NaN
6093       NaN
Name: Size[m], Length: 6094, dtype: float64

In [ ]:
#move 'size[m]' column next to the species column
size_to_move = data.pop('Size[m]')  # Remove the column
data.insert(16, 'Size[m]', size_to_move)

In [ ]:
#Load a good database containining a lot of possible species, and matching between what there is into the string
shark_species = pd.read_csv('/content/drive/MyDrive/DQ/project/shark_species.csv')
shark_species["SPECIES"] = shark_species["SPECIES"].str.strip()
shark_species["SPECIES"] = shark_species["SPECIES"].str.title()
shark_species

          SPECIES
0        Blacktip
1            Blue
2           Brown
3            Bull
4       Caribbean
5          Bronze
6           Dusky
7       Galapagos
8      Hammerhead
9            Grey
10          Lemon
11        Leopard
12       Whitetip
13      Sharpnose
14        Oceanic
15        Pacific
16         Pyjama
17          Tiger
18     Sharptooth
19          Silky
20      Silvertip
21    Smoothhound
22        Spinner
23           Horn
24      Bluntnose
25      Broadnose
26        Frilled
27        Basking
28         Bigeye
29      Crocodile
30         Goblin
31        Longfin
32      Megamouth
33      Porbeagle
34         Salmon
35       Shortfin
36          White
37       Bluegrey
38      Epaulette
39          Nurse
40        Spotted
41          Tawny
42          Whale
43   Whitespotted
44          Zebra
45       Sawshark
46        Bramble
47   Cookiecutter
48   Lanternshark
49         Gulper
50        Kitefin
51          Pygmy
52          Spiny
53          Angel
54      Blacknose
55           Mako
56   Smooth Hound
57  White Spotted
58        Lantern
59           Gill

In [ ]:
for i, s in enumerate(data["Species"]):
    s = str(s)
    s = s.title()
    matching_element = set(shark_species["SPECIES"]).intersection(s.split())
    if matching_element:
        data.loc[i, "Species"] = matching_element.pop()
    else:
        data.loc[i, "Species"] = np.nan

##INVESTIGATOR

In [ ]:
data["Investigator or Source"]

0                         WA Today, 6/11/2017
1                                         NaN
2       Daytona Beach News-Journal, 6/10/2017
3                              C. Moore, GSAF
4                         Nine News, 6/7/2017
                        ...
6089         H. Taunton; N. Bartlett,  p. 234
6090    H. Taunton; N. Bartlett,  pp. 233-234
6091     F. Schwartz, p.23; C. Creswell, GSAF
6092                      The Sun, 10/20/1938
6093                               S.W. Baker
Name: Investigator or Source, Length: 6094, dtype: object

In [ ]:
data["Investigator or Source"] = data["Investigator or Source"].str.replace(";",",")

In [ ]:
def standardize_investigator(investigator):
    if(pd.isna(investigator)):
      return np.nan
    investigator = re.sub(r'\b\d{1,2}[-/]\d{1,2}[-/]\d{4}\b', '', investigator)
    investigator = investigator.title()
    investigator = re.sub(r'\b(Pp?\. ?\d{1,}(-\d{1,})?)\b', '', investigator)

    return investigator


data["Investigator or Source"] = data["Investigator or Source"].apply(standardize_investigator)
data['Investigator or Source'] = data['Investigator or Source'].str.replace(r', ?,', ',', regex=True)
data["Investigator or Source"] = data['Investigator or Source'].str.strip(" ,")
data["Investigator or Source"]

0                             Wa Today
1                                  NaN
2           Daytona Beach News-Journal
3                       C. Moore, Gsaf
4                            Nine News
                     ...
6089           H. Taunton, N. Bartlett
6090           H. Taunton, N. Bartlett
6091    F. Schwartz, C. Creswell, Gsaf
6092                           The Sun
6093                        S.W. Baker
Name: Investigator or Source, Length: 6094, dtype: object

##pdf

In [ ]:
data["pdf"]

0                  2017.06.11-Goff.pdf
1            2017.06.10.b-Flinders.pdf
2               2017.06.10.a-Brock.pdf
3             2017.06.07.R-Thomson.pdf
4               2017.06.04-Simpson.pdf
                     ...
6089            ND-0005-RoebuckBay.pdf
6090                 ND-0004-Ahmun.pdf
6091    ND-0003-Ocracoke_1900-1905.pdf
6092        ND-0002-JulesPatterson.pdf
6093                ND-0001-Ceylon.pdf
Name: pdf, Length: 6094, dtype: object

In [ ]:
for s in data["pdf"]:
    s = str(s)
    if ".pdf" not in s:
        print(s)

2017.02.24-Mandurah
2016.05.02-NZ-pdf
2015.10.17.b.-Hawaii. pdf
2015.08.19-Szsarmack
2015.06.30.b-Steve.pf
2015.06.13-Specker
2014.10.17-Olsson, pdf
2014.08.09.R-Hindley, pdf
2014.05.14-McLeod, pdf
.2014.04.12.R-inflatable
2014.03.18.c-Borgna
2014.02.17.R-OneDLL
2014.01.26-O'Connor.pf
2014.01.25-Grant
2013.07.29.a-Gatewood
12.26
2008.07.26.a-Maui
1989.00.00.b-Halstead
1983.06.00-Starling
1962.08.30.b-pdf
1957.00.00.i-baby
1942.07.06-Bardolini
1905.07.00
1899.09.11.R-Guyot
1888.10.23.R-Croatia. Pdf
1863.00.00.R-Corfu
1823.10.07.R-Slaves
1788.05.10-Sydney
1638.00.00.R-Herbert

In [ ]:
data["pdf"] = data["pdf"].str.replace(" ",'')
data["pdf"] = data["pdf"].str.replace("-pdf",'.pdf')
data["pdf"] = data["pdf"].str.replace(",pdf",'.pdf')
data["pdf"] = data["pdf"].str.replace(".pf",'.pdf')
data["pdf"] = data["pdf"].str.replace(".Pdf",'.pdf')

In [ ]:
for i,s in enumerate(data["pdf"]):
    s = str(s)
    if ".pdf" not in s:
      data.loc[i,"pdf"]+= '.pdf'

##(4)DATA CLEANING (ERROR DETECTION&CORRECTION MISSING VALUES)

In [ ]:
data.isnull().sum()

Case Number                  0
Date                        26
Time                      3324
Year                         0
Country                     46
Area                       412
Location                   512
Type                         4
Activity                     0
Activity Detail            537
Name                      1752
Sex                        571
Age                       2737
Injury                      28
Fatal                       30
Species                   4432
Size[m]                   4019
Investigator or Source      17
pdf                          0
href                         0
dtype: int64

In [ ]:
data['Date'] = data['Date'].ffill()

In [ ]:
data['Time'] = data['Time'].fillna(pd.to_datetime("00:00", format='%H:%M').time())

In [ ]:
data['Type']=data['Type'].fillna(data['Type'].mode()[0])

In [ ]:
data['Activity Detail']=data['Activity Detail'].fillna('No detail')

In [ ]:
data['Injury']=data['Injury'].fillna("Unknown")

In [ ]:
data['Fatal']=data['Fatal'].fillna("Unknown")

In [ ]:
data['Country']=data['Country'].fillna("Unknown")

In [ ]:
data['Area']=data['Area'].fillna("Unknown")

In [ ]:
data['Location']=data['Location'].fillna("Unknown")

In [ ]:
data['Name']=data['Name'].fillna("Unknown")

In [ ]:
data['Sex']=data['Sex'].fillna("Not Specified")

In [ ]:
#try to use ml method to fill missing value in Age column
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Rows with missing Age (target for prediction)
missing_age = data[data['Age'].isna()]
# Rows without missing Age (training data)
non_missing_age = data[data['Age'].notna()]

# Select relevant features
features = ['Activity', 'Activity Detail', 'Type','Injury', 'Fatal']
X_train_full = non_missing_age[features]
y_train_full = non_missing_age['Age']
X_pred_full = missing_age[features]

# Encode Categorical Variables
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')  # Ensure dense output
X_train_encoded = encoder.fit_transform(X_train_full)
X_pred_encoded = encoder.transform(X_pred_full)

In [ ]:
# Split into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train_encoded, y_train_full, test_size=0.2, random_state=42)

In [ ]:
# Train and validate the model
model = RandomForestRegressor(n_estimators=100, random_state=42)  # Explicitly set estimators
model.fit(X_train, y_train)
y_val_pred = model.predict(X_val)

# Evaluate the model
print("Mean Squared Error:", mean_squared_error(y_val, y_val_pred))

Mean Squared Error: 229.9822964738409

In [ ]:
'''
# Predict missing Age values
predicted_ages = model.predict(X_pred_encoded)

# Fill missing Age values in the original dataset
data.loc[data['Age'].isna(), 'Age'] = predicted_ages
'''

"\n# Predict missing Age values\npredicted_ages = model.predict(X_pred_encoded)\n\n# Fill missing Age values in the original dataset\ndata.loc[data['Age'].isna(), 'Age'] = predicted_ages\n"

In [ ]:
data['Age']=data['Age'].fillna("Not Specified")

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Separate rows with and without missing values in Species
missing_species = data[data['Species'].isna()]
non_missing_species = data[data['Species'].notna()]

# Select features and target
features = ['Country','Area','Location','Activity','Activity Detail','Injury','Size[m]']
X_train_all = non_missing_species[features]
y_train_all = non_missing_species['Species']
X_pred_all = missing_species[features]

# Encode categorical variables in features
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_train_all)
X_pred_encoded = encoder.transform(X_pred_all)

# Encode the target variable (Species)
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train_all)

# Split data for training and validation
X_train, X_val, y_train, y_val = train_test_split(
    X_train_encoded, y_train_encoded, test_size=0.2, random_state=42
)

# Train a classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Validate the model
y_val_pred = model.predict(X_val)
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))

Validation Accuracy: 0.5705705705705706

In [ ]:
'''
# Predict missing Species values
predicted_species_encoded = model.predict(X_pred_encoded)

# Decode predictions back to original labels
predicted_species = label_encoder.inverse_transform(predicted_species_encoded)

# Fill missing Species values in the original dataset
data.loc[data['Species'].isna(), 'Species'] = predicted_species
'''

"\n# Predict missing Species values\npredicted_species_encoded = model.predict(X_pred_encoded)\n\n# Decode predictions back to original labels\npredicted_species = label_encoder.inverse_transform(predicted_species_encoded)\n\n# Fill missing Species values in the original dataset\ndata.loc[data['Species'].isna(), 'Species'] = predicted_species\n"

In [ ]:
data['Species']=data['Species'].fillna("Unknown")

In [ ]:
data['Size[m]'] = data['Size[m]'].fillna(data['Size[m]'].mean().round(2))

In [ ]:
data['Investigator or Source']=data['Investigator or Source'].fillna("Unknown")

In [ ]:
data.isnull().sum()

Case Number               0
Date                      0
Time                      0
Year                      0
Country                   0
Area                      0
Location                  0
Type                      0
Activity                  0
Activity Detail           0
Name                      0
Sex                       0
Age                       0
Injury                    0
Fatal                     0
Species                   0
Size[m]                   0
Investigator or Source    0
pdf                       0
href                      0
dtype: int64

##(5) DATA CLEANING (ERROR DETECTION&CORRECTION OUTLIERS)

In [ ]:
maxyear=data['Year'].max()
maxyear

2017

In [ ]:
data.loc[data['Date']>pd.Timestamp('2017-12-31'),['Case Number','Date','Year']]

     Case Number       Date  Year
91    2016.09.00 2020-09-16  2016
231   2015.09.00 2020-09-15  2015
364   2014.09.00 2020-09-14  2014
385   2014.08.00 2020-08-14  2014
579   2012.12.00 2020-12-12  2012
...          ...        ...   ...
5353  1904.09.00 2020-09-04  1904
5354  1904.08.00 2020-08-04  1904
5366  1903.07.00 2020-07-03  1903
5383  1902.06.00 2020-06-02  1902
5384  1902.04.00 2020-04-02  1902

[216 rows x 3 columns]

In [ ]:
# Check if date is greater than 2017-12-31 and replace year with Year column value
def replace_year_if_needed(row):
    if row['Date'] > pd.Timestamp('2017-12-31'):
        # Replace the year in the date with the year from the 'Year' column
        return row['Date'].replace(year=row['Year'])
    else:
        return row['Date']

data['Date'] = data.apply(replace_year_if_needed, axis=1)

In [ ]:
#replace Year with year value in the Date column
data['Year']=data['Date'].dt.year

In [ ]:
# Convert the Year column to integers
data['Year'] = pd.to_numeric(data['Year']).astype('Int64')

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Size[m],Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,White,4.0000,Wa Today,2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,Unknown,F,Not Specified,"No injury, knocke off board",NO,Gill,7.0000,Unknown,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,Unknown,12.6200,Daytona Beach News-Journal,2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,Unknown,3.0000,"C. Moore, Gsaf",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,Not Specified,Laceration to shin,NO,Unknown,2.4384,Nine News,2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,Australia,Western Australia,Unknown,Unprovoked,Diving,Pearl diving,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"F. Schwartz, C. Creswell, Gsaf",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,Panama,Unknown,"Panama Bay N, W",Unprovoked,Other,No detail,Jules Patterson,M,Not Specified,,YES,Unknown,12.6200,The Sun,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,No detail,Unknown,M,15,". ""Shark bit him in half, carrying away the lo...",YES,Unknown,12.6200,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

##(6) DATA CLEANING (DATA DEDUPLICATION)

In [ ]:
!pip install recordlinkage

Collecting recordlinkage
  Downloading recordlinkage-0.16-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: jellyfish>=1 in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (1.1.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (1.26.4)
Requirement already satisfied: pandas<3,>=1 in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (2.2.2)
Requirement already satisfied: scipy>=1 in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (1.13.1)
Requirement already satisfied: scikit-learn>=1 in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (1.6.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from recordlinkage) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1->recordlinkage) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1->recordlinkage) (1.17.0)
Downloading recordlinkage-0.16-py3-none-any.whl (926 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.9/926.9 kB 11.1 MB/s eta 0:00:00
Installing collected packages: recordlinkage
Successfully installed recordlinkage-0.16

In [ ]:
import recordlinkage

In [ ]:
data = data.drop_duplicates()
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Size[m],Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,White,4.0000,Wa Today,2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,Unknown,F,Not Specified,"No injury, knocke off board",NO,Gill,7.0000,Unknown,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,Unknown,12.6200,Daytona Beach News-Journal,2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,Unknown,3.0000,"C. Moore, Gsaf",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,Not Specified,Laceration to shin,NO,Unknown,2.4384,Nine News,2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,Australia,Western Australia,Unknown,Unprovoked,Diving,Pearl diving,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"F. Schwartz, C. Creswell, Gsaf",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,Panama,Unknown,"Panama Bay N, W",Unprovoked,Other,No detail,Jules Patterson,M,Not Specified,,YES,Unknown,12.6200,The Sun,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,No detail,Unknown,M,15,". ""Shark bit him in half, carrying away the lo...",YES,Unknown,12.6200,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
indexer = recordlinkage.index.SortedNeighbourhood(
        on='href', window=21)

candidate_links = indexer.index(data)
candidate_links

<ipython-input-138-0c6b04fe96dd>:1: DeprecationWarning: The argument 'on' is deprecated. Use 'left_on=...' and 'right_on=None' to simulate the behaviour of 'on'.
  indexer = recordlinkage.index.SortedNeighbourhood(

MultiIndex([(   9,    0),
            (  10,    1),
            (  11,    2),
            (  12,    3),
            (  13,    4),
            (  14,    5),
            (  15,    6),
            (  16,    7),
            (  17,    8),
            (  19,   18),
            ...
            (6084, 5968),
            (6085, 5973),
            (6086, 5967),
            (6087, 5972),
            (6088, 5971),
            (6089, 5970),
            (6090,    0),
            (6091,    1),
            (6092,    2),
            (6093, 5983)],
           length=60986)

In [ ]:
data.columns

Index(['Case Number', 'Date', 'Time', 'Year', 'Country', 'Area', 'Location',
       'Type', 'Activity', 'Activity Detail', 'Name', 'Sex', 'Age', 'Injury',
       'Fatal', 'Species', 'Size[m]', 'Investigator or Source', 'pdf', 'href'],
      dtype='object')

In [ ]:
compare_cl = recordlinkage.Compare()

compare_cl.exact('Case Number', 'Case Number', label='Case Number')
compare_cl.exact('Date', 'Date', label='Date')
compare_cl.exact('Time', 'Time', label='Time')
compare_cl.exact('Year', 'Year', label='Year')
compare_cl.exact('Type', 'Type', label='Type')
compare_cl.exact('Activity', 'Activity', label='Activity')
compare_cl.exact('Activity Detail', 'Activity Detail', label='Activity Detail')
compare_cl.exact('Sex', 'Sex', label='Sex')
compare_cl.exact('Age', 'Age', label='Age')
compare_cl.exact('Fatal', 'Fatal', label='Fatal')
compare_cl.exact('Species', 'Species', label='Species')
compare_cl.exact('Size[m]', 'Size[m]', label='Size[m]')

compare_cl.string('Country', 'Country', method='jarowinkler', threshold=0.9, label='Country')
compare_cl.string('Area', 'Area', method='jarowinkler', threshold=0.9, label='Area')
compare_cl.string('Location', 'Location', method='jarowinkler', threshold=0.9, label='Location')
compare_cl.string('Name', 'Name', method='jarowinkler', threshold=0.9, label='Name')
compare_cl.string('Injury', 'Injury', method='jarowinkler', threshold=0.9, label='Injury')
compare_cl.string('Investigator or Source', 'Investigator or Source', method='jarowinkler', threshold=0.9, label='Investigator or Source')
compare_cl.string('pdf', 'pdf', method='jarowinkler', threshold=0.9, label='pdf')

In [ ]:
features = compare_cl.compute(candidate_links, data)
matches = features[features.sum(axis=1) > 15]
matches

,,Case Number,Date,Time,Year,Type,Activity,Activity Detail,Sex,Age,Fatal,Species,Size[m],Country,Area,Location,Name,Injury,Investigator or Source,pdf
5318,5316,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0
6060,6058,0,1,1,1,1,1,1,1,1,0,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
6087,6085,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0
429,428,0,1,0,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
643,642,0,1,1,1,1,1,1,1,1,1,0,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
981,980,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0
1068,1067,0,1,1,1,1,1,1,1,0,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1539,1538,0,1,1,1,0,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
1927,1926,0,0,1,1,1,1,1,1,1,1,1,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1952,1951,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0
2039,2037,0,1,1,1,1,0,1,1,0,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2494,2493,1,1,1,1,1,1,0,0,1,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,0.0
3226,3225,0,1,1,1,1,1,1,1,0,1,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0
3232,3231,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,1.0,1.0,0.0
4099,4098,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0
4188,4187,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0
4383,4382,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,0.0,1.0,0.0,1.0,1.0
4546,4545,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4622,4621,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,0.0,0.0,1.0,1.0
4645,4644,0,0,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4849,4848,0,1,1,1,1,1,1,0,1,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,0.0
5017,5016,0,1,1,1,1,1,1,0,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
5433,5432,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0
5552,5551,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,1.0,0.0,1.0
5807,5806,0,0,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6086,6085,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0
6087,6086,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
5294,5293,1,1,1,1,1,1,1,1,1,0,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0
5610,5609,0,1,1,1,1,1,1,1,1,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0

In [ ]:
# Drop duplicates (e.g., keep the first occurrence)
duplicate_indices = matches.index.get_level_values(1)
data= data.drop(duplicate_indices)

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Size[m],Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Australia,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,White,4.0000,Wa Today,2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Australia,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,Unknown,F,Not Specified,"No injury, knocke off board",NO,Gill,7.0000,Unknown,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Usa,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,Unknown,12.6200,Daytona Beach News-Journal,2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,United Kingdom,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,Unknown,3.0000,"C. Moore, Gsaf",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,Usa,Florida,"Middle Sambo Reef Off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,Not Specified,Laceration to shin,NO,Unknown,2.4384,Nine News,2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,Australia,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,Australia,Western Australia,Unknown,Unprovoked,Diving,Pearl diving,Unknown,M,Not Specified,,YES,Unknown,12.6200,"H. Taunton, N. Bartlett",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,Usa,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Unknown,M,Not Specified,,YES,Unknown,12.6200,"F. Schwartz, C. Creswell, Gsaf",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,Panama,Unknown,"Panama Bay N, W",Unprovoked,Other,No detail,Jules Patterson,M,Not Specified,,YES,Unknown,12.6200,The Sun,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,Sri Lanka,Eastern Province,"Below The English Fort, Trincomalee",Unprovoked,Swimming,No detail,Unknown,M,15,". ""Shark bit him in half, carrying away the lo...",YES,Unknown,12.6200,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

##DQ Assessment

In [ ]:
for col in data.columns:
    print("DQ Assessment for "+col+":")

    DISTINCT = (data[col].nunique())
    COUNT = data[col].count()
    ROWS = len(data[col])
    UNIQUENESS = DISTINCT / ROWS
    print("UNIQUENESS: ", UNIQUENESS)

    DISTINCTNESS = DISTINCT / COUNT
    print("DISTINCTNESS: ", DISTINCTNESS)

    MAX_COUNTS = max(data[col].value_counts())
    CONSTANCY = MAX_COUNTS / COUNT
    print("CONSTANCY: ", CONSTANCY)

    COMPLETENESS = COUNT / ROWS
    print("COMPLETENESS: ", COMPLETENESS)

    print("\n\n")

DQ Assessment for Case Number:
UNIQUENESS:  0.9978565539983512
DISTINCTNESS:  0.9978565539983512
CONSTANCY:  0.00032976092333058534
COMPLETENESS:  1.0



DQ Assessment for Date:
UNIQUENESS:  0.8314921681780709
DISTINCTNESS:  0.8314921681780709
CONSTANCY:  0.0018136850783182193
COMPLETENESS:  1.0



DQ Assessment for Time:
UNIQUENESS:  0.04023083264633141
DISTINCTNESS:  0.04023083264633141
CONSTANCY:  0.5437757625721352
COMPLETENESS:  1.0



DQ Assessment for Year:
UNIQUENESS:  0.036108821104699096
DISTINCTNESS:  0.036108821104699096
CONSTANCY:  0.04402308326463314
COMPLETENESS:  1.0



DQ Assessment for Country:
UNIQUENESS:  0.030667765869744436
DISTINCTNESS:  0.030667765869744436
CONSTANCY:  0.35449299258037925
COMPLETENESS:  1.0



DQ Assessment for Area:
UNIQUENESS:  0.12728771640560593
DISTINCTNESS:  0.12728771640560593
CONSTANCY:  0.16718878812860677
COMPLETENESS:  1.0



DQ Assessment for Location:
UNIQUENESS:  0.636603462489695
DISTINCTNESS:  0.636603462489695
CONSTANCY:  0.08359439406430338
COMPLETENESS:  1.0



DQ Assessment for Type:
UNIQUENESS:  0.000494641384995878
DISTINCTNESS:  0.000494641384995878
CONSTANCY:  0.7333882934872218
COMPLETENESS:  1.0



DQ Assessment for Activity:
UNIQUENESS:  0.0021434460016488046
DISTINCTNESS:  0.0021434460016488046
CONSTANCY:  0.20395713107996702
COMPLETENESS:  1.0



DQ Assessment for Activity Detail:
UNIQUENESS:  0.240560593569662
DISTINCTNESS:  0.240560593569662
CONSTANCY:  0.5614179719703215
COMPLETENESS:  1.0



DQ Assessment for Name:
UNIQUENESS:  0.705358615004122
DISTINCTNESS:  0.705358615004122
CONSTANCY:  0.2852431986809563
COMPLETENESS:  1.0



DQ Assessment for Sex:
UNIQUENESS:  0.000494641384995878
DISTINCTNESS:  0.000494641384995878
CONSTANCY:  0.8065952184666118
COMPLETENESS:  1.0



DQ Assessment for Age:
UNIQUENESS:  0.013355317394888705
DISTINCTNESS:  0.013355317394888705
CONSTANCY:  0.4474855729596043
COMPLETENESS:  1.0



DQ Assessment for Injury:
UNIQUENESS:  0.5752679307502061
DISTINCTNESS:  0.5752679307502061
CONSTANCY:  0.1259686727122836
COMPLETENESS:  1.0



DQ Assessment for Fatal:
UNIQUENESS:  0.0006595218466611707
DISTINCTNESS:  0.0006595218466611707
CONSTANCY:  0.7230008244023083
COMPLETENESS:  1.0



DQ Assessment for Species:
UNIQUENESS:  0.00560593569661995
DISTINCTNESS:  0.00560593569661995
CONSTANCY:  0.7269579554822754
COMPLETENESS:  1.0



DQ Assessment for Size[m]:
UNIQUENESS:  0.02671063478977741
DISTINCTNESS:  0.02671063478977741
CONSTANCY:  0.6586974443528442
COMPLETENESS:  1.0



DQ Assessment for Investigator or Source:
UNIQUENESS:  0.5523495465787304
DISTINCTNESS:  0.5523495465787304
CONSTANCY:  0.01615828524319868
COMPLETENESS:  1.0



DQ Assessment for pdf:
UNIQUENESS:  0.9985160758450123
DISTINCTNESS:  0.9985160758450123
CONSTANCY:  0.00032976092333058534
COMPLETENESS:  1.0



DQ Assessment for href:
UNIQUENESS:  0.9985160758450123
DISTINCTNESS:  0.9985160758450123
CONSTANCY:  0.00032976092333058534
COMPLETENESS:  1.0

In [ ]:
data.to_csv("/path/to/your/drive/cleaned_attacks.csv", index=False)