In [1]:
from google.colab import drive # Mounte personal Gdrive folder
drive.mount('/content/drive')

Mounted at /content/drive

###Install lib, import module and read data

In [4]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.12.2-py2.py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib>=3.5 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.10.6)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (3.1.5)
Collecting visions<0.8.0,>=0.7.5 (from visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling)
  Downloading visions-0.7.6-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.26.4)
Collecting htmlmin==0.1.12 (from ydata-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling)
  Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (4.4.1)
Collecting imagehash==4.3.1 (from ydata-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.11/dist-packages (from ydata-profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata-profiling)
  Downloading dacite-1.9.1-py3-none-any.whl.metadata (17 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling)
  Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (4.55.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.5->ydata-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling) (2025.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2024.12.14)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.0,>=0.7.5->visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling) (25.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.11/dist-packages (from visions<0.8.0,>=0.7.5->visions[type_image_path]<0.8.0,>=0.7.5->ydata-profiling) (3.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.12.2-py2.py3-none-any.whl (390 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.9/390.9 kB 12.7 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 20.0 MB/s eta 0:00:00
Downloading dacite-1.9.1-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (687 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 35.1 MB/s eta 0:00:00
Downloading visions-0.7.6-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 9.0 MB/s eta 0:00:00
Downloading pywavelets-1.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 53.9 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=9df5f273f44616095c1b9f6968cf5cd14ada617a56331cee46d5c09dfb8db953
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: htmlmin, PyWavelets, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed PyWavelets-1.8.0 dacite-1.9.1 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.4 visions-0.7.6 ydata-profiling-4.12.2

In [5]:
import pandas as pd
from ydata_profiling import ProfileReport
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import re
%matplotlib inline

In [10]:
data = pd.read_csv('https://raw.githubusercontent.com/zyl009/DATA-AND-INFORMATION-QUALITY-PROJECT/refs/heads/main/attacks.csv')

In [8]:
data= pd.DataFrame(data)

###DATA EXPLORATION

In [9]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2017.06.11,2017-06-11,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,...,N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6095
1,2017.06.10.b,2017-06-10,2017.0,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,...,N,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.b,2017.06.10.b,6094
2,2017.06.10.a,2017-06-10,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,...,N,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.a,2017.06.10.a,6093
3,2017.06.07.R,Reported 07-Jun-2017,2017.0,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,...,N,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.07.R,2017.06.07.R,6092
4,2017.06.04,2017-06-04,2017.0,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,...,N,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.04,2017.06.04,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6
6090,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5
6091,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4
6092,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3
6093,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2

In [ ]:
data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [ ]:
data.shape

(6094, 22)

In [ ]:
data.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order              int64
dtype: object

In [ ]:
data.describe()

              Year  original order
count  6092.000000     6094.000000
mean   1926.197308     3048.499672
std     284.366422     1759.331064
min       0.000000        2.000000
25%    1942.000000     1525.250000
50%    1976.000000     3048.500000
75%    2004.000000     4571.750000
max    2017.000000     6095.000000

In [ ]:
data.duplicated().any()

False

###(1)PROFILING

In [ ]:
PROFILE = ProfileReport(data, title="Pandas Profiling Report")
PROFILE.to_file("/content/drive/MyDrive/DQ/project/profiling.html")
PROFILE

Output hidden; open in https://colab.research.google.com to view.

###(2)DQ ASSESSMENT

In [ ]:
for col in data.columns:
    print("DQ Assessment for "+col+":")

    DISTINCT = (data[col].nunique())
    COUNT = data[col].count()
    ROWS = len(data[col])
    UNIQUENESS = DISTINCT / ROWS
    print("UNIQUENESS: ", UNIQUENESS)

    DISTINCTNESS = DISTINCT / COUNT
    print("DISTINCTNESS: ", DISTINCTNESS)

    MAX_COUNTS = max(data[col].value_counts())
    CONSTANCY = MAX_COUNTS / COUNT
    print("CONSTANCY: ", CONSTANCY)

    NOT_NULL = data.count().sum()
    NULL = data.isnull().sum().sum()
    TOT = data.shape[0]*data.shape[1]
    COMPLETENESS = NOT_NULL / TOT
    print("COMPLETENESS: ", COMPLETENESS)

    print("\n\n")

DQ Assessment for Case Number:
UNIQUENESS:  0.9973744666885461
DISTINCTNESS:  0.9973744666885461
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  0.9154831876361249



DQ Assessment for Date:
UNIQUENESS:  0.8528060387266163
DISTINCTNESS:  0.8528060387266163
CONSTANCY:  0.0018050541516245488
COMPLETENESS:  0.9154831876361249



DQ Assessment for Year:
UNIQUENESS:  0.03938299967180833
DISTINCTNESS:  0.03939592908732764
CONSTANCY:  0.02314510833880499
COMPLETENESS:  0.9154831876361249



DQ Assessment for Type:
UNIQUENESS:  0.0009845749917952085
DISTINCTNESS:  0.0009852216748768472
CONSTANCY:  0.7333333333333333
COMPLETENESS:  0.9154831876361249



DQ Assessment for Country:
UNIQUENESS:  0.033475549721037084
DISTINCTNESS:  0.03373015873015873
CONSTANCY:  0.35714285714285715
COMPLETENESS:  0.9154831876361249



DQ Assessment for Area:
UNIQUENESS:  0.13111256974072857
DISTINCTNESS:  0.14061950017599437
CONSTANCY:  0.1786342837029215
COMPLETENESS:  0.9154831876361249



DQ Assessment for Location:
UNIQUENESS:  0.6537577945520184
DISTINCTNESS:  0.7135948414830736
CONSTANCY:  0.029016657710908115
COMPLETENESS:  0.9154831876361249



DQ Assessment for Activity:
UNIQUENESS:  0.2466360354446997
DISTINCTNESS:  0.2703723691311387
CONSTANCY:  0.16747616477783775
COMPLETENESS:  0.9154831876361249



DQ Assessment for Name:
UNIQUENESS:  0.834591401378405
DISTINCTNESS:  0.8637907608695652
CONSTANCY:  0.0859375
COMPLETENESS:  0.9154831876361249



DQ Assessment for Sex :
UNIQUENESS:  0.0009845749917952085
DISTINCTNESS:  0.001087547580206634
CONSTANCY:  0.8892514047489578
COMPLETENESS:  0.9154831876361249



DQ Assessment for Age:
UNIQUENESS:  0.02477847062684608
DISTINCTNESS:  0.044754001185536456
CONSTANCY:  0.045050385299347954
COMPLETENESS:  0.9154831876361249



DQ Assessment for Injury:
UNIQUENESS:  0.5981293075155891
DISTINCTNESS:  0.6008902077151336
CONSTANCY:  0.12298054731289153
COMPLETENESS:  0.9154831876361249



DQ Assessment for Fatal (Y/N):
UNIQUENESS:  0.0014768624876928126
DISTINCTNESS:  0.001484168865435356
CONSTANCY:  0.7241094986807388
COMPLETENESS:  0.9154831876361249



DQ Assessment for Time:
UNIQUENESS:  0.059074499507712507
DISTINCTNESS:  0.12640449438202248
CONSTANCY:  0.06355337078651685
COMPLETENESS:  0.9154831876361249



DQ Assessment for Species :
UNIQUENESS:  0.25500492287495896
DISTINCTNESS:  0.5014520813165537
CONSTANCY:  0.05292029686995805
COMPLETENESS:  0.9154831876361249



DQ Assessment for Investigator or Source:
UNIQUENESS:  0.7927469642271087
DISTINCTNESS:  0.7949646207010038
CONSTANCY:  0.015961823268059897
COMPLETENESS:  0.9154831876361249



DQ Assessment for pdf:
UNIQUENESS:  0.9981949458483754
DISTINCTNESS:  0.9981949458483754
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  0.9154831876361249



DQ Assessment for href formula:
UNIQUENESS:  0.9980308500164096
DISTINCTNESS:  0.9981946495978993
CONSTANCY:  0.0003282455276546857
COMPLETENESS:  0.9154831876361249



DQ Assessment for href:
UNIQUENESS:  0.9970462750246144
DISTINCTNESS:  0.9972099130149352
CONSTANCY:  0.0006564910553093714
COMPLETENESS:  0.9154831876361249



DQ Assessment for Case Number.1:
UNIQUENESS:  0.9972103708565803
DISTINCTNESS:  0.9972103708565803
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  0.9154831876361249



DQ Assessment for Case Number.2:
UNIQUENESS:  0.9973744666885461
DISTINCTNESS:  0.9973744666885461
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  0.9154831876361249



DQ Assessment for original order:
UNIQUENESS:  0.9998359041680341
DISTINCTNESS:  0.9998359041680341
CONSTANCY:  0.0003281916639317361
COMPLETENESS:  0.9154831876361249

#(3) DATA CLEANING (DATA TRANSFORMATION)

In [ ]:
# Remove leading/trailing spaces for every col
for col in data.columns:
    if data[col].dtype == 'object':  # Check if the column contains string data
        data[col] = data[col].str.strip()

In [ ]:
#Remove specific symbols: @#$%^*�!? for every col
# function to clean special symbols
def remove_special_symbols(text):
    if pd.isna(text):  # Skip NaN values
        return text
    # Remove specific symbols: @#$%^*�!?
    text = re.sub(r'[#$%^*@�!?]', '', str(text))
    return text

# Apply cleaning to all object (text-based) columns
for col in data.select_dtypes(include=['object']).columns:
    data[col] = data[col].apply(remove_special_symbols)

##case number column

In [ ]:
data['Case Number'].equals(data['Case Number.1'].equals(data['Case Number.2']))

False

In [ ]:
data['Case Number'].equals(data['Case Number.1'])

False

In [ ]:
data['Case Number.1'].equals(data['Case Number.2'])

False

In [ ]:
data['Case Number'].isin(data['Case Number.1']).value_counts()

Case Number
True     6079
False      15
Name: count, dtype: int64

In [ ]:
data['Case Number'].isin(data['Case Number.2']).value_counts()

Case Number
True     6092
False       2
Name: count, dtype: int64

In [ ]:
data['Case Number.1'].isin(data['Case Number.2']).value_counts()

Case Number.1
True     6082
False      12
Name: count, dtype: int64

In [ ]:
#since Case Number, Case NumberN.1 and Case Number N.2 are similar, and they are just the number of the case, delete the Case Number.1 and Case Number.2
data=data.drop(['Case Number.1','Case Number.2'],axis=1)

##Date and Year and Time column

###normalize the date

In [ ]:
# Function to normalize date
def normalize_date(value):
    # Dictionary for month corrections and seasons mapping
    month_corrections = {
        "Jut": "Jul",
        "rch": "Mar",
        "ept": "Sep",
        "prr": "Apr",
        }
    seasons_mapping = {
        "Winter": "12-01",
        "Spring": "03-01",
        "Summer": "06-01",
        "Fall": "09-01",
    }

    # Correct common typos
    for typo, correct in month_corrections.items():
        value = value.replace(typo, correct)

    # Patterns
    season_year_pattern = r'(Winter|Spring|Summer|Fall)[^\d]*(\d{4})'  # e.g., Winter 1942
    day_month_year_pattern = r'(\d{1,2})-([A-Za-z]{3})-(\d{4})'  # e.g., 19-Jul-1913
    month_year_pattern = r'([A-Za-z]{3})-(\d{4})'  # e.g., Aug-1987
    year_pattern = r'(\d{4})'  # e.g., 1901

    try:
       # Handle YYYY-MM-DD (already formatted)
        if re.match(r'^\d{4}-\d{2}-\d{2}$', value):
            return value
        # Check if the value matches the format 'YYYY.MM.DD'
        match = re.match(r'^(\d{4})\.(\d{2})\.(\d{2})$', value)
        if match:
            year, month, day = match.groups()
            # Replace invalid month/day components
            month = '01' if month == '00' else month
            day = '01' if day == '00' else day
            return f"{year}-{month}-{day}"  # Return in 'YYYY-MM-DD' format
        # Match season and year
        match = re.search(season_year_pattern, value, re.IGNORECASE)
        if match:
            season, year = match.groups()
            month_day = seasons_mapping[season.capitalize()]
            return f"{year}-{month_day}"
        # Handle phrases like 'mid-1870s'
        if "mid" in value:
            match = re.search(r'(\d{4})', value)
            if match:
                year = match.group(1)
                return f"{year}-06-01"  # Approximate mid-year date

        # Match day-month-year
        match = re.search(day_month_year_pattern, value)
        if match:
            day, month, year = match.groups()
            month_num = datetime.strptime(month, "%b").month
            return f"{year}-{month_num:02d}-{int(day):02d}"

        # Match month-year
        match = re.search(month_year_pattern, value)
        if match:
            month, year = match.groups()
            month_num = datetime.strptime(month, "%b").month
            return f"{year}-{month_num:02d}-01"

        # Match year only
        match = re.search(year_pattern, value)
        if match:
            year = match.group(1)
            return f"{year}-01-01"

    except Exception as e:
        # Log unexpected errors for debugging
        print(f"Error processing value: {value}. Error: {e}")

    # Return None for unprocessable rows
    return np.nan

In [ ]:
# Example DataFrame
sampledata = pd.DataFrame({
    'Date': [
        '1986-01-02','2008.01.30','No date (3 days after preceding incident) & prior to 19-Jul-1913','Before 1903','Reported 09-Aprr-1855',
        'No date, Before Aug-1987', '1950s', '2003?', 'Ca. 1543','Circa 500 A.D.', 'Ca. 336.B.C.', 'Before Feb-1998', '190Feb-2010',
        'During the war 1943-1945','Summer-2008','25-Jut-1881','Reported 30-March-1878','Ca. mid-1870s','Reported 03-Sept-1816','Fall 1943','early winter 1993'
    ]
})

# Apply the function to the Date column
sampledata['Normalized Date'] = sampledata['Date'].apply(normalize_date)

# Display the updated DataFrame
sampledata

                                                 Date Normalized Date
0                                          1986-01-02      1986-01-02
1                                          2008.01.30      2008-01-30
2   No date (3 days after preceding incident) & pr...      1913-07-19
3                                         Before 1903      1903-01-01
4                               Reported 09-Aprr-1855      1855-04-01
5                            No date, Before Aug-1987      1987-08-01
6                                               1950s      1950-01-01
7                                               2003?      2003-01-01
8                                            Ca. 1543      1543-01-01
9                                      Circa 500 A.D.             NaN
10                                       Ca. 336.B.C.             NaN
11                                    Before Feb-1998      1998-02-01
12                                        190Feb-2010      2010-02-01
13                           During the war 1943-1945      1943-01-01
14                                        Summer-2008      2008-06-01
15                                        25-Jut-1881      1881-07-25
16                             Reported 30-March-1878      1878-03-01
17                                      Ca. mid-1870s      1870-06-01
18                              Reported 03-Sept-1816      1816-09-01
19                                          Fall 1943      1943-09-01
20                                  early winter 1993      1993-12-01

In [ ]:
# Apply the function to the Date column
data['Date'] = data['Date'].apply(normalize_date)

In [ ]:
# Convert Date column to datetime
data['Date']= pd.to_datetime(data['Date'],format='%Y-%m-%d',errors='coerce')

In [ ]:
data

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2017.06.11,2017-06-11,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6095
1,2017.06.10.b,2017-06-10,2017.0,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6094
2,2017.06.10.a,2017-06-10,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6093
3,2017.06.07.R,2017-06-07,2017.0,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6092
4,2017.06.04,2017-06-04,2017.0,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
6090,ND.0004,1903-01-01,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5
6091,ND.0003,1900-01-01,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
6092,ND.0002,1883-01-01,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8N, 79W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
6093,ND.0001,1845-01-01,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2

In [ ]:
# Convert the 'Year' column to integers (handling invalid or non-numeric values)
data['Year'] = pd.to_numeric(data['Year'], errors='coerce').fillna(0).astype(int)

###Time

In [ ]:
#move Time column next to the Date column
Time_to_move = data.pop('Time')  # Remove the column
data.insert(2, 'Time', Time_to_move)

In [ ]:
data['Time'].isnull().sum()

3246

In [ ]:
# Function to normalize time
def normalize_time(value):
    # Ensure the value is a string
    if not isinstance(value, str):
        return np.nan
    # Regex to find time already in HH:MM format
    match = re.search(r'\b(\d{1,2}):(\d{2})\b', value)
    if match:
        hour, minute = match.groups()
        return f"{int(hour):02d}:{int(minute):02d}"  # Return valid HH:MM format

    # Regex to find valid time patterns like hh:mm or hhm
    match = re.search(r'(\d{1,2})h(\d{2})', value)
    if match:
        hour, minute = match.groups()
        return f"{int(hour):02d}:{int(minute):02d}"

    # Map descriptions to approximate times
    time_map = {
        'early morning': '06:00',
        'late morning': '10:30',
        'morning': '08:00',
        'early afternoon': '13:00',
        'late afternoon': '16:30',
        'afternoon': '15:00',
        'late evening': '21:00',
        'evening': '19:00',
        'dusk': '18:30',
        'night': '22:00',
        'noon': '12:00',
        'midnight': '00:00'
      }
    for key, mapped_time in time_map.items():
        if key in value.lower():
            return mapped_time


    # Return None for unprocessable rows
    return np.nan


# Sample data
sampledTime = pd.DataFrame({
    'Time': ['08h00', 'wwwda15h00bdbgrfd', '15h45lll', 'Dusk','dusklllll', 'morning', 'MORNING','late late Late morning', 'siskks early afternoon', 'kcdoak night 6154', 'unknown']
})

# Apply normalization
sampledTime['Normalized Time'] = sampledTime['Time'].apply(normalize_time)
sampledTime

                      Time Normalized Time
0                    08h00           08:00
1        wwwda15h00bdbgrfd           15:00
2                 15h45lll           15:45
3                     Dusk           18:30
4                dusklllll           18:30
5                  morning           08:00
6                  MORNING           08:00
7   late late Late morning           10:30
8   siskks early afternoon           13:00
9        kcdoak night 6154           22:00
10                 unknown             NaN

In [ ]:
data['Time']=data['Time'].apply(normalize_time)

In [ ]:
data['Time']=pd.to_datetime(data['Time'],format='%H:%M',errors='coerce').dt.time

In [ ]:
data

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href formula,href,original order
0,2017.06.11,2017-06-11,08:30:00,2017,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6095
1,2017.06.10.b,2017-06-10,15:45:00,2017,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6094
2,2017.06.10.a,2017-06-10,10:00:00,2017,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6093
3,2017.06.07.R,2017-06-07,NaT,2017,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6092
4,2017.06.04,2017-06-04,NaT,2017,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6091
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6
6090,ND.0004,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5
6091,ND.0003,1900-01-01,NaT,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,4
6092,ND.0002,1883-01-01,NaT,0,Unprovoked,PANAMA,NaN,"Panama Bay 8N, 79W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,3
6093,ND.0001,1845-01-01,NaT,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2

##Country, Area and Location column

In [ ]:
data["Country"] = data['Country'].str.upper()
data.loc[data['Country'] == 'ENGLAND', 'Country'] = 'UNITED KINGDOM'
data.loc[data['Country'] == 'SCOTLAND', 'Country'] = 'UNITED KINGDOM'
data.loc[data['Country'] == 'BETWEEN PORTUGAL & INDIA', 'Country'] = 'PORTUGAL / INDIA'
data.loc[data['Country'] == 'CEYLON SRI LANKA', 'Country'] = 'SRI LANKA'

##href column

In [ ]:
data['href formula'].equals(data['href'])

False

In [ ]:
data['href formula'].isin(data['href']).value_counts()

href formula
True     6040
False      54
Name: count, dtype: int64

In [ ]:
data.loc[data['href formula'] != data['href'], ['href formula', 'href']]

,href formula,href
0,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
8,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
35,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
99,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
106,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
141,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
187,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
194,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
214,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
261,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
313,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
344,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
345,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
346,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
353,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
354,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
375,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
387,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
405,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
430,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
444,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
445,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
446,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
447,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
448,http://sharkattackfile.net/spreadsheets/pdf_di...,pdf_directory2014.01.04-Riano.pdf
460,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
461,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
462,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
463,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
464,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
465,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
466,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
467,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
531,pdf-directory/2013.05.27.b-Ena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
532,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
906,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1301,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1302,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2561,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3103,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3104,VALUE,http://sharkattackfile.net/spreadsheets/pdf_di...
3633,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3687,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4001,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4012,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4479,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4728,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4754,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4805,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5403,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5545,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5773,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN
5781,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5913,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5959,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
#replace with correct value in href
data.loc[531,'href formula']=data['href'][531]
data.loc[3103,'href formula']=data['href'][3103]
data.loc[3104,'href formula']=data['href'][3104]

In [ ]:
#find rows where the 'href formular' column does not start with 'http'
invalid_urls = data[~data['href formula'].str.startswith('http', na=False)]
# Display rows with invalid URLs
invalid_urls

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href formula,href,original order
6008,ND.0100,2003-01-01,NaT,0,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,Spearfishing,C.D. Dollar,M,NaN,Swim fin bitten,N,1.8 m [6'] shark,"R.D. Weeks, GSAF",ND-0100-CDDollar.pdf,Q93http://sharkattackfile.net/spreadsheets/pdf...,Q93http://sharkattackfile.net/spreadsheets/pdf...,87

In [ ]:
data.loc[6008,'href formula']=data.loc[6008,'href formula'].lstrip('Q93')
data.loc[6008,'href formula']

'http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0100-CDDollar.pdf'

In [ ]:
#delete href column since it is similar with href formula, and href fomula is more clean
del(data['href'])

In [ ]:
#rename href formula with href
data.rename(columns={'href formula': 'href'}, inplace=True)

In [ ]:
#Deleted the column 'original order' as it was uniformly distributed, not useful
del(data['original order'])

In [ ]:
data

,Case Number,Date,Time,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,Unprovoked,PANAMA,NaN,"Panama Bay 8N, 79W",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

##Type and Activity column

In [ ]:
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Invalid', 'Boat', 'Sea Disaster',
       'Boating'], dtype=object)

In [ ]:
#Type is related to the activity,  move 'Type' column next to the Activity column
Type_to_move = data.pop('Type')  # Remove the column
data.insert(7, 'Type', Type_to_move)

In [ ]:
data.insert(9,'Activity Detail',data['Activity'])

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Body boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Spearfishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,AUSTRALIA,Western Australia,NaN,Unprovoked,Pearl diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,NaN,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data['Activity'].unique()

array(['Body boarding', 'Surfing', 'Spearfishing', ...,
       'Crew swimming alongside their anchored ship',
       '4 men were bathing', 'Wreck of  large double sailing canoe'],
      dtype=object)

In [ ]:
#main activity are swimming, Diving,surfing，boarding, fishing, Wading，Walking,Standing，Snorkeling，Bathing and Other
# Update the Activity column based on conditions
data['Activity'] = np.where(
    data['Activity'].str.contains('Swimming', case=False, na=False), 'Swimming',
    np.where(
        data['Activity'].str.contains('Diving', case=False, na=False), 'Diving',
        np.where(
        data['Activity'].str.contains('Surfing', case=False, na=False), 'Surfing',
        np.where(
        data['Activity'].str.contains('Boarding', case=False, na=False), 'Boarding',
        np.where(
        data['Activity'].str.contains('Fishing', case=False, na=False), 'Fishing',
        np.where(
        data['Activity'].str.contains('Wading', case=False, na=False), 'Wading',
        np.where(
        data['Activity'].str.contains('Walking', case=False, na=False), 'Walking',
        np.where(
        data['Activity'].str.contains('Standing', case=False, na=False), 'Standing',
        np.where(
        data['Activity'].str.contains('Snorkeling', case=False, na=False), 'Snorkeling',
        np.where(
        data['Activity'].str.contains('Bathing', case=False, na=False), 'Bathing',
        'Other'
))))))))))

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,Surfing,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,Surfing,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,Surfing,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,Diving,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
#set No detail in Activity Detail column when data is the same in Activity and Activity Detail column
data.loc[data['Activity Detail'].str.lower()==data['Activity'].str.lower(),'Activity Detail']='No detail'

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Invalid', 'Boat', 'Sea Disaster',
       'Boating'], dtype=object)

In [ ]:
data.loc[data['Type']=='Invalid',['Type','Activity','Activity Detail']]

         Type  Activity Activity Detail
12    Invalid   Surfing       No detail
18    Invalid     Other     Photo shoot
20    Invalid  Swimming       No detail
26    Invalid    Diving    Scuba Diving
52    Invalid   Fishing    Spearfishing
...       ...       ...             ...
5941  Invalid   Bathing       No detail
5951  Invalid     Other             NaN
5957  Invalid     Other  Went overboard
6019  Invalid    Diving    Scuba diving
6024  Invalid    Diving       No detail

[529 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Boat',['Type','Activity','Activity Detail']]

      Type Activity                        Activity Detail
44    Boat  Fishing                          Kayak fishing
45    Boat    Other                         Tagging sharks
83    Boat  Fishing                              No detail
101   Boat    Other                               Kayaking
108   Boat  Fishing  Fishing in Alabama Deep Fishing Rodeo
...    ...      ...                                    ...
5925  Boat    Other                                    NaN
5932  Boat  Fishing                              No detail
5939  Boat    Other                                    NaN
6004  Boat  Fishing                              No detail
6066  Boat  Fishing                    Wooden fishing boat

[202 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Boating',['Type','Activity','Activity Detail']]

         Type  Activity                                    Activity Detail
4109  Boating   Fishing                                   Longling fishing
4111  Boating   Fishing                                          No detail
4114  Boating     Other                                            Boating
4131  Boating     Other                                       Ocean racing
4132  Boating   Fishing                                Fishing for pompano
...       ...       ...                                                ...
5715  Boating   Fishing                                          No detail
5720  Boating   Fishing                                          No detail
5722  Boating     Other  Fleet of canoes caught by a squall and charged...
5765  Boating   Fishing                                          No detail
5766  Boating  Boarding                                    Boarding a ship

[110 rows x 3 columns]

In [ ]:
data.loc[data['Type']=='Sea Disaster',['Type','Activity','Activity Detail']]

              Type  Activity                               Activity Detail
325   Sea Disaster     Other                                           NaN
448   Sea Disaster     Other                                  Sea disaster
751   Sea Disaster     Other                                  Sea disaster
1018  Sea Disaster     Other                                  Air Disaster
1049  Sea Disaster     Other          Sinking of the cargo ship Mark Jason
...            ...       ...                                           ...
5973  Sea Disaster     Other                                           NaN
6051  Sea Disaster     Other    A group of survivors on a raft for 17-days
6061  Sea Disaster     Other                                           NaN
6063  Sea Disaster     Other                        Spent 8 days in dinghy
6064  Sea Disaster  Swimming  Aircraft ditched in the sea, swimming ashore

[220 rows x 3 columns]

In [ ]:
#set boat as boating
data.loc[data['Type']=='Boat','Type']='Boating'

In [ ]:
# Update 'Activity' where 'Activity' is 'Other' and 'Type' is 'Boating' or 'Sea Distaster'
data.loc[(data['Activity'] == 'Other') & (data['Type'] == 'Boating'), 'Activity'] = 'Boating'
data.loc[(data['Activity'] == 'Other') & (data['Type'] =='Sea Disaster'),'Activity']='Sea Disaster'
#set No detail in Activity Detail column when data is the same in Activity and Activity Detail column
data.loc[data['Activity Detail'].str.lower()==data['Activity'].str.lower(),'Activity Detail']='No detail'

In [ ]:
#set Invalid, Boating and sea disaster as Unknown
data.loc[data['Type']=='Invalid','Type']='Unknown'
data.loc[data['Type']=='Boating','Type']='Unknown'
data.loc[data['Type']=='Sea Disaster','Type']='Unknown'
data['Type'].unique()

array(['Unprovoked', 'Provoked', nan, 'Unknown'], dtype=object)

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal (Y/N),Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",N,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",N,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,N,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,NaT,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",N,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,NaT,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,N,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,NaT,0,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,NaT,0,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,NaT,0,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,FATAL,Y,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,NaT,0,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,NaT,0,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data.loc[data['Location'].str.contains('County',case=False,na=False),'Location']

2                           Ponce Inlet, Volusia County
4       Middle Sambo Reef off Boca Chica, Monroe County
6                            Awendaw, Charleston County
12                          Sunset Beach, Orange County
13                         San Onofre, San Diego County
                             ...
6018                   Riviera Beach, Palm Beach County
6022                          LaJolla, San Diego County
6025       Mosquito Inlet (Ponce Inlet), Volusia County
6037                          Capistrano, Orange County
6041                      Palm Beach, Palm Beach County
Name: Location, Length: 1434, dtype: object

##Injury and Fatal column

In [ ]:
data['Injury'].nunique()

3576

In [ ]:
# Remove 'PROVOKED INCIDENT' and the associated comma (if present)
data['Injury'] = data['Injury'].str.replace(r'(\s*,\s*)?PROVOKED INCIDENT(\s*,\s*)?', '', regex=True).str.strip()
data['Injury'] = data['Injury'].str.replace(r'(\s*,\s*)?FATAL(\s*,\s*)?', '', regex=True).str.strip()

In [ ]:
data['Fatal (Y/N)'].unique()

array(['N', 'Y', nan, 'UNKNOWN', '2017', 'F', 'VALUE', 'n'], dtype=object)

In [ ]:
data.rename(columns={'Fatal (Y/N)': 'Fatal'}, inplace=True)

In [ ]:
data.loc[data['Fatal']=='2017',['Injury','Fatal']]

                                       Injury Fatal
646  Lower left leg injured PROVOKED ACCIDENT  2017

In [ ]:
data.loc[data['Fatal']=='F',['Injury','Fatal']]

                          Injury Fatal
4779  human remains washed ahore     F

In [ ]:
data.loc[data['Fatal']=='VALUE',['Injury','Fatal']]

                                                 Injury  Fatal
5548  Forensic evidence indicated death resulted fro...  VALUE

In [ ]:
data.loc[data['Fatal']=='n',['Injury','Fatal']]

                  Injury Fatal
5870  Lacerations to leg     n

In [ ]:
data.loc[data['Fatal']=='N','Fatal']= 'NO'
data.loc[data['Fatal']=='Y','Fatal']= 'YES'
data.loc[data['Fatal']=='2017','Fatal']= 'NO'
data.loc[data['Fatal']=='F','Fatal']='YES'
data.loc[data['Fatal']=='VALUE','Fatal']='NO'
data.loc[data['Fatal']=='n','Fatal']='NO'

In [ ]:
data['Fatal'].unique()

array(['NO', 'YES', nan, 'UNKNOWN'], dtype=object)

##(4)DATA CLEANING (ERROR DETECTION&CORRECTION MISSING VALUES)

In [ ]:
data.isnull().sum()

Case Number                  0
Date                        26
Time                      3324
Year                         0
Country                     46
Area                       412
Location                   511
Type                         4
Activity                     0
Activity Detail            535
Name                       206
Sex                        577
Age                       2720
Injury                      28
Fatal                       30
Species                   2995
Investigator or Source      17
pdf                          0
href                         0
dtype: int64

In [ ]:
data['Date'] = data['Date'].ffill()

In [ ]:
data['Time']=data['Time'].fillna("00:00:00")

In [ ]:
data['Type']=data['Type'].fillna(data['Type'].mode()[0])

In [ ]:
data['Activity Detail']=data['Activity Detail'].fillna('No detail')

In [ ]:
data['Injury']=data['Injury'].fillna("Unknown")

In [ ]:
data['Fatal']=data['Fatal'].fillna("Unknown")

##(5) DATA CLEANING (ERROR DETECTION&CORRECTION OUTLIERS)

In [ ]:
maxyear=data['Year'].max()
maxyear

2017

In [ ]:
data.loc[data['Date']>pd.Timestamp('2017-12-31'),'Date']

91     2020-09-16
231    2020-09-15
364    2020-09-14
385    2020-08-14
579    2020-12-12
          ...
5353   2020-09-04
5354   2020-08-04
5366   2020-07-03
5383   2020-06-02
5384   2020-04-02
Name: Date, Length: 216, dtype: datetime64[ns]

In [ ]:
# Check if date is greater than 2017-12-31 and replace year with Year column value
def replace_year_if_needed(row):
    if row['Date'] > pd.Timestamp('2017-12-31'):
        # Replace the year in the date with the year from the 'Year' column
        return row['Date'].replace(year=row['Year'])
    else:
        return row['Date']

data['Date'] = data.apply(replace_year_if_needed, axis=1)

In [ ]:
#replace Year with year value in the Date column
data['Year']=data['Date'].dt.year

In [ ]:
# Convert the Year column to integers
data['Year'] = pd.to_numeric(data['Year']).astype('Int64')

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",NO,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,NO,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,,YES,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,No detail,Jules Patterson,M,NaN,,YES,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,". ""Shark bit him in half, carrying away the lo...",YES,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
data.isnull().sum()

Case Number                  0
Date                         0
Time                         0
Year                         0
Country                     46
Area                       412
Location                   511
Type                         0
Activity                     0
Activity Detail              0
Name                       206
Sex                        577
Age                       2720
Injury                       0
Fatal                        0
Species                   2995
Investigator or Source      17
pdf                          0
href                         0
dtype: int64

##(6) DATA CLEANING (DATA DEDUPLICATION)

In [ ]:
!pip install recordlinkage

Requirement already satisfied: recordlinkage in /usr/local/lib/python3.10/dist-packages (0.16)
Requirement already satisfied: jellyfish>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.1.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.26.4)
Requirement already satisfied: pandas<3,>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (2.2.2)
Requirement already satisfied: scipy>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.13.1)
Requirement already satisfied: scikit-learn>=1 in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.6.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from recordlinkage) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1->recordlinkage) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1->recordlinkage) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1->recordlinkage) (1.17.0)

In [ ]:
import recordlinkage

In [ ]:
data = data.drop_duplicates()
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",NO,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,NO,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,,YES,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,No detail,Jules Patterson,M,NaN,,YES,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,". ""Shark bit him in half, carrying away the lo...",YES,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [ ]:
indexer = recordlinkage.index.SortedNeighbourhood(
        on='href', window=9)

candidate_links = indexer.index(data)
candidate_links

<ipython-input-200-5f9154a8a561>:1: DeprecationWarning: The argument 'on' is deprecated. Use 'left_on=...' and 'right_on=None' to simulate the behaviour of 'on'.
  indexer = recordlinkage.index.SortedNeighbourhood(

MultiIndex([(   4,    0),
            (   5,    1),
            (   6,    2),
            (   7,    3),
            (   8,    4),
            (   9,    6),
            (  10,    7),
            (  11,    8),
            (  13,    9),
            (  14,   10),
            ...
            (5967,    0),
            (5970,    3),
            (5971,    2),
            (5972,    1),
            (5973, 5970),
            (6089,  323),
            (6090, 5968),
            (6091, 5973),
            (6092, 5967),
            (6093, 5977)],
           length=24412)

In [ ]:
data.columns

Index(['Case Number', 'Date', 'Time', 'Year', 'Country', 'Area', 'Location',
       'Type', 'Activity', 'Activity Detail', 'Name', 'Sex ', 'Age', 'Injury',
       'Fatal', 'Species ', 'Investigator or Source', 'pdf', 'href'],
      dtype='object')

In [ ]:
compare_cl = recordlinkage.Compare()

compare_cl.exact('Case Number', 'Case Number', label='Case Number')
compare_cl.exact('Date', 'Date', label='Date')
compare_cl.exact('Time', 'Time', label='Time')
compare_cl.exact('Year', 'Year', label='Year')
compare_cl.exact('Type', 'Type', label='Type')
compare_cl.exact('Activity', 'Activity', label='Activity')
compare_cl.exact('Activity Detail', 'Activity Detail', label='Activity Detail')
compare_cl.exact('Age', 'Age', label='Age')
compare_cl.exact('Fatal', 'Fatal', label='Fatal')

compare_cl.string('Country', 'Country', method='jarowinkler', threshold=0.9, label='Country')
compare_cl.string('Area', 'Area', method='jarowinkler', threshold=0.9, label='Area')
compare_cl.string('Location', 'Location', method='jarowinkler', threshold=0.9, label='Location')
compare_cl.string('Name', 'Name', method='jarowinkler', threshold=0.9, label='Name')
compare_cl.string('Injury', 'Injury', method='jarowinkler', threshold=0.9, label='Injury')

In [ ]:
features = compare_cl.compute(candidate_links, data)
matches = features[features.sum(axis=1) > 11]
matches

,,Case Number,Date,Time,Year,Type,Activity,Activity Detail,Age,Fatal,Country,Area,Location,Name,Injury
1068,1067,0,1,1,1,1,1,1,0,1,1.0,1.0,1.0,1.0,1.0
2494,2493,1,1,1,1,1,1,0,1,1,1.0,1.0,1.0,0.0,1.0
4546,4545,0,1,1,1,1,1,1,0,1,1.0,1.0,1.0,1.0,1.0
5552,5551,0,1,1,1,1,1,1,0,1,1.0,1.0,1.0,1.0,1.0

In [ ]:
# Drop duplicates (e.g., keep the first occurrence)
duplicate_indices = matches.index.get_level_values(1)
data= data.drop(duplicate_indices)

In [ ]:
data

,Case Number,Date,Time,Year,Country,Area,Location,Type,Activity,Activity Detail,Name,Sex,Age,Injury,Fatal,Species,Investigator or Source,pdf,href
0,2017.06.11,2017-06-11,08:30:00,2017,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Unprovoked,Boarding,Body boarding,Paul Goff,M,48,"No injury, board bitten",NO,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2017.06.10.b,2017-06-10,15:45:00,2017,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Unprovoked,Surfing,No detail,female,F,NaN,"No injury, knocke off board",NO,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2017.06.10.a,2017-06-10,10:00:00,2017,USA,Florida,"Ponce Inlet, Volusia County",Unprovoked,Surfing,No detail,Bryan Brock,M,19,Laceration to left foot,NO,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2017.06.07.R,2017-06-07,00:00:00,2017,UNITED KINGDOM,South Devon,Bantham Beach,Unprovoked,Surfing,No detail,Rich Thomson,M,30,"Bruise to leg, cuts to hand sustained when he ...",NO,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2017.06.04,2017-06-04,00:00:00,2017,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Unprovoked,Fishing,Spearfishing,Parker Simpson,M,NaN,Laceration to shin,NO,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6089,ND.0005,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,Roebuck Bay,Unprovoked,Diving,No detail,male,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6090,ND.0004,1903-01-01,00:00:00,1903,AUSTRALIA,Western Australia,NaN,Unprovoked,Diving,Pearl diving,Ahmun,M,NaN,,YES,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6091,ND.0003,1900-01-01,00:00:00,1900,USA,North Carolina,Ocracoke Inlet,Unprovoked,Swimming,No detail,Coast Guard personnel,M,NaN,,YES,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6092,ND.0002,1883-01-01,00:00:00,1883,PANAMA,NaN,"Panama Bay 8N, 79W",Unprovoked,Other,No detail,Jules Patterson,M,NaN,,YES,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6093,ND.0001,1845-01-01,00:00:00,1845,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Unprovoked,Swimming,No detail,male,M,15,". ""Shark bit him in half, carrying away the lo...",YES,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...